import { VisualizationIR, VisualizationLayer, KeyframedProperty } from "./types.js";
import { parseHexColor } from "./color-utils.js";

/**
 * REQ-025 §59-§63: Transpilador ExtendScript JSX determinista para Adobe After Effects.
 * Genera scripts de composición 100% vectoriales, con Motion Blur y sandbox seguro.
 */

export class VisualizationJsxCompiler {
  public static compileToJsx(ir: VisualizationIR): string {
    const lines: string[] = [];
    const compName = this.sanitizeString(`[DV] ${ir.type} - ${ir.id}`);
    const fps = 30;

    // Encabezado y Sandbox
    lines.push("// ============================================================================");
    lines.push(`// Generated by Motion Graphics Engine v4.0.0 — Data Visualization JSX Compiler`);
    lines.push(`// Visualization ID: ${ir.id} (${ir.type})`);
    lines.push(`// Canonical SHA-256 Checksum: ${ir.checksumSha256}`);
    lines.push("// ============================================================================");
    lines.push("");
    lines.push(`app.beginUndoGroup('Generate DataViz: ${compName}');`);
    lines.push("try {");
    lines.push("  var project = app.project || app.newProject();");
    lines.push(
      `  var comp = project.items.addComp('${compName}', ${ir.width}, ${ir.height}, 1.0, ${ir.durationSeconds.toFixed(3)}, ${fps});`
    );
    lines.push("  comp.motionBlur = true; // Obligatorio per USER_DESIGN_PREFERENCES.md");
    lines.push("");

    // Ordenar capas por zIndex ascendente
    const sortedLayers = [...ir.layers].sort((a, b) => a.zIndex - b.zIndex);

    for (let i = 0; i < sortedLayers.length; i++) {
      const layer = sortedLayers[i];
      const layerVar = `layer_${this.sanitizeVarName(layer.id)}_${i}`;

      lines.push(`  // --- Layer: ${layer.name} (${layer.type}) ---`);

      if (layer.type === "TEXT" && layer.text) {
        const textContent = this.sanitizeString(layer.text.content);
        lines.push(`  var ${layerVar} = comp.layers.addText('${textContent}');`);
        lines.push(`  ${layerVar}.name = '${this.sanitizeString(layer.name)}';`);
        lines.push(`  ${layerVar}.motionBlur = true;`);
        lines.push(`  var textProp_${i} = ${layerVar}.property('Source Text');`);
        lines.push(`  var textDoc_${i} = textProp_${i}.value;`);
        lines.push(`  textDoc_${i}.fontSize = ${layer.text.fontSize};`);
        lines.push(`  textDoc_${i}.font = '${this.sanitizeString(layer.text.fontFamily)}';`);
        const rgb = this.hexToAeRgb(layer.text.color);
        lines.push(`  textDoc_${i}.fillColor = [${rgb.join(", ")}];`);
        if (layer.text.tracking) {
          lines.push(`  textDoc_${i}.tracking = ${layer.text.tracking * 10};`);
        }
        if (layer.text.alignment === "CENTER") {
          lines.push(`  textDoc_${i}.justification = ParagraphJustification.CENTER_JUSTIFY;`);
        } else if (layer.text.alignment === "RIGHT") {
          lines.push(`  textDoc_${i}.justification = ParagraphJustification.RIGHT_JUSTIFY;`);
        } else {
          lines.push(`  textDoc_${i}.justification = ParagraphJustification.LEFT_JUSTIFY;`);
        }
        lines.push(`  textProp_${i}.setValue(textDoc_${i});`);
      } else if (layer.geometry?.kind === "RECT") {
        const rect = layer.geometry;
        const rgb = this.hexToAeRgb(rect.fillColor || "#FFFFFF");
        const w = Math.max(1, rect.width);
        const h = Math.max(1, rect.height);
        lines.push(`  var ${layerVar} = comp.layers.addSolid([${rgb.join(", ")}], '${this.sanitizeString(layer.name)}', ${w}, ${h}, 1.0);`);
        lines.push(`  ${layerVar}.motionBlur = true;`);
      } else {
        // Fallback genérico shape layer
        lines.push(`  var ${layerVar} = comp.layers.addShape();`);
        lines.push(`  ${layerVar}.name = '${this.sanitizeString(layer.name)}';`);
        lines.push(`  ${layerVar}.motionBlur = true;`);
      }

      // Transformaciones estándar
      lines.push(
        `  ${layerVar}.property('Transform').property('Position').setValue([${layer.transform.position.x}, ${layer.transform.position.y}]);`
      );
      lines.push(
        `  ${layerVar}.property('Transform').property('Opacity').setValue(${layer.opacity * 100});`
      );

      // Keyframes
      if (layer.animation?.properties) {
        for (const prop of layer.animation.properties) {
          this.transpileKeyframes(lines, layerVar, prop);
        }
      }

      lines.push("");
    }

    lines.push("} catch (err) {");
    lines.push("  alert('Error en DataViz ExtendScript: ' + err.toString());");
    lines.push("} finally {");
    lines.push("  app.endUndoGroup();");
    lines.push("}");

    return lines.join("\n");
  }

  private static transpileKeyframes(lines: string[], layerVar: string, prop: KeyframedProperty): void {
    let aePropName = "";
    if (prop.property === "opacity") aePropName = "Opacity";
    else if (prop.property === "scale.y" || prop.property === "scale.x") aePropName = "Scale";
    else if (prop.property === "counterValue") return; // Manejado por expresión o texto dinámico
    else return;

    for (const kf of prop.keyframes) {
      let valStr = "";
      if (aePropName === "Opacity" && typeof kf.value === "number") {
        valStr = (kf.value * 100).toString();
      } else if (aePropName === "Scale" && typeof kf.value === "number") {
        valStr = prop.property === "scale.y"
          ? `[100, ${(kf.value * 100).toFixed(1)}]`
          : `[${(kf.value * 100).toFixed(1)}, 100]`;
      } else {
        valStr = Array.isArray(kf.value) ? `[${kf.value.join(", ")}]` : String(kf.value);
      }
      lines.push(
        `  ${layerVar}.property('Transform').property('${aePropName}').setValueAtTime(${kf.timeSeconds.toFixed(3)}, ${valStr});`
      );
    }
  }

  private static hexToAeRgb(hex: string): [string, string, string] {
    try {
      const { r, g, b } = parseHexColor(hex);
      return [
        (r / 255).toFixed(3),
        (g / 255).toFixed(3),
        (b / 255).toFixed(3),
      ];
    } catch {
      return ["1.0", "1.0", "1.0"];
    }
  }

  private static sanitizeString(str: string): string {
    return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, " ");
  }

  private static sanitizeVarName(str: string): string {
    return str.replace(/[^a-zA-Z0-9_]/g, "_");
  }
}
