import { DataVizIR } from "../types.js";

/**
 * REQ-025 §59 to §62: After Effects DataViz ExtendScript JSX Compiler.
 * Zero-inference compiler transpiling DataVizIR AST into executable ExtendScript JSX.
 */
export class AfterEffectsDataVizCompiler {
  public static compileToJsx(ir: DataVizIR): string {
    const lines: string[] = [];
    const compName = this.escapeString(ir.metadata.title ?? `[DTV] ${ir.type}`);
    const { width, height, fps, durationSeconds } = ir.composition;

    // Header & Security Sandbox Notice (§62)
    lines.push("// ============================================================================");
    lines.push(`// Generated by Motion Graphics Engine v4.0.0 — DataViz AE JSX Compiler`);
    lines.push(`// Visualization ID: ${ir.id} (${ir.type})`);
    lines.push(`// Checksum SHA-256: ${ir.checksumSha256 ?? "N/A"}`);
    lines.push("// ============================================================================");
    lines.push("");
    lines.push(`app.beginUndoGroup('Build DataViz - ${compName}');`);
    lines.push("try {");
    lines.push("  var project = app.project || app.newProject();");
    lines.push(`  var comp = project.items.addComp('${compName}', ${width}, ${height}, 1.0, ${durationSeconds.toFixed(3)}, ${fps});`);
    lines.push("  comp.motionBlur = true; // Required per USER_DESIGN_PREFERENCES.md");
    lines.push("");

    // Background Solid if specified
    if (ir.style.backgroundColor && ir.style.backgroundColor !== "transparent") {
      const rgb = this.hexToRgbNormalized(ir.style.backgroundColor);
      lines.push(`  // Background Solid`);
      lines.push(`  var bgLayer = comp.layers.addSolid([${rgb.join(", ")}], '[DTV] BACKGROUND', ${width}, ${height}, 1.0);`);
      lines.push(`  bgLayer.moveToEnd();`);
      lines.push("");
    }

    // Materialize Elements in deterministic order (§60, §61)
    lines.push("  // Materialize Visual Elements (Anti-Divergence Rule)");
    let barIndex = 1;
    let labelIndex = 1;
    let valueIndex = 1;

    for (const el of ir.elements) {
      if (el.type === "BAR") {
        const barName = `[DTV] BAR ${String(barIndex++).padStart(3, "0")}`;
        const rgb = this.hexToRgbNormalized((el.properties.color as string) ?? ir.style.primaryColor);
        const w = Number((el.bounds?.width ?? 20).toFixed(2));
        const h = Number((el.bounds?.height ?? 100).toFixed(2));
        const x = Number((el.position.x + w / 2).toFixed(2));
        const y = Number((el.position.y + h / 2).toFixed(2));

        lines.push(`  // --- ${barName} ---`);
        lines.push(`  var bar_${el.id} = comp.layers.addSolid([${rgb.join(", ")}], '${barName}', ${w}, ${h}, 1.0);`);
        lines.push(`  bar_${el.id}.motionBlur = true;`);
        lines.push(`  bar_${el.id}.property('Transform').property('Position').setValue([${x}, ${y}]);`);

        // Check if there is an animation targeting this bar
        const anim = ir.animations.find((a) => a.targetId === el.id);
        if (anim && anim.property === "SCALE") {
          const fromScale = Array.isArray(anim.from) ? anim.from : [anim.from, anim.from];
          const toScale = Array.isArray(anim.to) ? anim.to : [anim.to, anim.to];
          lines.push(`  var scaleProp_${el.id} = bar_${el.id}.property('Transform').property('Scale');`);
          lines.push(`  scaleProp_${el.id}.setValueAtTime(${anim.startSeconds.toFixed(3)}, [${(fromScale[0] * 100).toFixed(1)}, ${(fromScale[1] * 100).toFixed(1)}]);`);
          lines.push(`  scaleProp_${el.id}.setValueAtTime(${anim.endSeconds.toFixed(3)}, [${(toScale[0] * 100).toFixed(1)}, ${(toScale[1] * 100).toFixed(1)}]);`);
        }
        lines.push("");
      } else if (el.type === "COUNTER" || el.type === "CARD") {
        const valName = `[DTV] VALUE ${String(valueIndex++).padStart(3, "0")}`;
        const displayVal = this.escapeString(String(el.properties.displayValue ?? el.properties.rawNumericValue ?? ""));
        const fontSize = (el.properties.fontSize as number) ?? ir.style.valueSize;
        const fontName = this.escapeString((el.properties.fontFamily as string) ?? ir.style.titleFontFamily);
        const posX = Number(el.position.x.toFixed(2));
        const posY = Number(el.position.y.toFixed(2));

        lines.push(`  // --- ${valName} ---`);
        lines.push(`  var text_${el.id} = comp.layers.addText('${displayVal}');`);
        lines.push(`  text_${el.id}.name = '${valName}';`);
        lines.push(`  text_${el.id}.property('Transform').property('Position').setValue([${posX}, ${posY}]);`);
        lines.push(`  var textProp_${el.id} = text_${el.id}.property('Text').property('Source Text');`);
        lines.push(`  var textDoc_${el.id} = textProp_${el.id}.value;`);
        lines.push(`  textDoc_${el.id}.fontSize = ${fontSize};`);
        lines.push(`  textDoc_${el.id}.font = '${fontName}';`);
        lines.push(`  textDoc_${el.id}.justification = ParagraphJustification.CENTER_JUSTIFY;`);
        lines.push(`  textProp_${el.id}.setValue(textDoc_${el.id});`);
        lines.push("");
      } else if (el.type === "LABEL") {
        const lblName = `[DTV] LABEL ${String(labelIndex++).padStart(3, "0")}`;
        const textContent = this.escapeString(String(el.properties.text ?? ""));
        const fontSize = (el.properties.fontSize as number) ?? ir.style.labelSize;
        const posX = Number(el.position.x.toFixed(2));
        const posY = Number(el.position.y.toFixed(2));

        lines.push(`  // --- ${lblName} ---`);
        lines.push(`  var lbl_${el.id} = comp.layers.addText('${textContent}');`);
        lines.push(`  lbl_${el.id}.name = '${lblName}';`);
        lines.push(`  lbl_${el.id}.property('Transform').property('Position').setValue([${posX}, ${posY}]);`);
        lines.push(`  var lblProp_${el.id} = lbl_${el.id}.property('Text').property('Source Text');`);
        lines.push(`  var lblDoc_${el.id} = lblProp_${el.id}.value;`);
        lines.push(`  lblDoc_${el.id}.fontSize = ${fontSize};`);
        lines.push(`  lblProp_${el.id}.setValue(lblDoc_${el.id});`);
        lines.push("");
      } else if (el.type === "AXIS" || el.type === "DIVIDER") {
        const elemName = el.type === "AXIS" ? "[DTV] AXIS" : "[DTV] DIVIDER";
        const w = Number((el.bounds?.width ?? width).toFixed(2));
        const h = Number((el.bounds?.height ?? 2).toFixed(2));
        const x = Number((el.position.x + w / 2).toFixed(2));
        const y = Number((el.position.y + h / 2).toFixed(2));
        const rgb = this.hexToRgbNormalized((el.properties.color as string) ?? "#FF1424");

        lines.push(`  // --- ${elemName} ---`);
        lines.push(`  var line_${el.id} = comp.layers.addSolid([${rgb.join(", ")}], '${elemName}', ${w}, ${h}, 1.0);`);
        lines.push(`  line_${el.id}.property('Transform').property('Position').setValue([${x}, ${y}]);`);
        lines.push("");
      } else if (el.type === "NODE" || el.type === "POINT") {
        const nodeName = `[DTV] NODE`;
        const radius = Number((el.properties.radius as number ?? 6).toFixed(2));
        const x = Number(el.position.x.toFixed(2));
        const y = Number(el.position.y.toFixed(2));
        const rgb = this.hexToRgbNormalized((el.properties.color as string) ?? "#FFFFFF");

        lines.push(`  // --- ${nodeName} ---`);
        lines.push(`  var node_${el.id} = comp.layers.addSolid([${rgb.join(", ")}], '${nodeName}', ${radius * 2}, ${radius * 2}, 1.0);`);
        lines.push(`  node_${el.id}.property('Transform').property('Position').setValue([${x}, ${y}]);`);
        lines.push("");
      }
    }

    lines.push("  app.endUndoGroup();");
    lines.push("} catch (err) {");
    lines.push("  app.endUndoGroup();");
    lines.push("  alert('Fatal error constructing DataViz: ' + err.toString());");
    lines.push("}");
    lines.push("");

    return lines.join("\n");
  }

  private static escapeString(str: string): string {
    return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\n/g, "\\n");
  }

  private static hexToRgbNormalized(hex: string): [string, string, string] {
    let clean = hex.replace("#", "").trim();
    if (clean.length === 3) {
      clean = clean[0] + clean[0] + clean[1] + clean[1] + clean[2] + clean[2];
    }
    const num = parseInt(clean, 16);
    const r = ((num >> 16) & 255) / 255.0;
    const g = ((num >> 8) & 255) / 255.0;
    const b = (num & 255) / 255.0;
    return [r.toFixed(3), g.toFixed(3), b.toFixed(3)];
  }
}
