import { EditorialIR } from "../ir/editorial-ir.types.js";

/**
 * REQ-025: Universal Multi-Format After Effects ExtendScript JSX Exporter v4.
 * Compiles the Editorial IR into executable ExtendScript JSX, strictly adhering to
 * USER_DESIGN_PREFERENCES.md (motion blur, centered anchor points, audio levels).
 */
export class JsxExporterV4 {
  public static exportToJsx(ir: EditorialIR): string {
    const { metadata, tracks } = ir;
    const { width, height, frameRate, title } = metadata;

    // Calculate total timeline duration from maximum outPoint across all tracks
    let maxDuration = 10.0;
    for (const track of tracks) {
      for (const clip of track.clips) {
        const end = clip.timelineRange.startSeconds + clip.timelineRange.durationSeconds;
        if (end > maxDuration) {
          maxDuration = end;
        }
      }
    }

    const lines: string[] = [];

    // Header & Safety
    lines.push("// ============================================================================");
    lines.push(`// Generated by Motion Graphics Engine v4.0.0 — Universal Editorial JSX Exporter`);
    lines.push(`// Project ID: ${ir.projectId}`);
    lines.push(`// Checksum: ${ir.checksum}`);
    lines.push("// ============================================================================");
    lines.push("");
    lines.push("app.beginUndoGroup('Build Master Composition - " + this.escapeString(title) + "');");
    lines.push("");
    lines.push("try {");
    lines.push("  var project = app.project || app.newProject();");
    lines.push("");
    lines.push("  // 1. Create Master Composition");
    lines.push(`  var compWidth = ${width};`);
    lines.push(`  var compHeight = ${height};`);
    lines.push(`  var compFps = ${frameRate};`);
    lines.push(`  var compDuration = ${maxDuration.toFixed(3)};`);
    lines.push(`  var masterComp = project.items.addComp('${this.escapeString(title)}', compWidth, compHeight, 1.0, compDuration, compFps);`);
    lines.push("  masterComp.motionBlur = true; // Mandatory per USER_DESIGN_PREFERENCES.md");
    lines.push("");

    // Build layers per track
    lines.push("  // 2. Timeline Tracks & Media Layers");
    let layerIndex = 1;

    for (const track of tracks) {
      lines.push(`  // --- Track: ${this.escapeString(track.name)} (${track.type}) ---`);

      for (const clip of track.clips) {
        const inPoint = clip.sourceRange.startSeconds;
        const duration = clip.timelineRange.durationSeconds;
        const startTime = clip.timelineRange.startSeconds;
        const volumeDb = clip.volumeDb;

        lines.push(`  // Clip: ${this.escapeString(clip.label)}`);
        lines.push(`  try {`);
        lines.push(`    var fileRef_${layerIndex} = new File('${this.escapeString(clip.assetId)}');`);
        lines.push(`    var footage_${layerIndex} = project.importFile(new ImportOptions(fileRef_${layerIndex}));`);
        lines.push(`    var layer_${layerIndex} = masterComp.layers.add(footage_${layerIndex});`);
        lines.push(`    layer_${layerIndex}.name = '${this.escapeString(clip.label)}';`);
        lines.push(`    layer_${layerIndex}.startTime = ${startTime.toFixed(3)} - ${inPoint.toFixed(3)};`);
        lines.push(`    layer_${layerIndex}.inPoint = ${startTime.toFixed(3)};`);
        lines.push(`    layer_${layerIndex}.outPoint = ${(startTime + duration).toFixed(3)};`);
        lines.push(`    layer_${layerIndex}.motionBlur = true;`);

        if (track.type.startsWith("VIDEO")) {
          // Centering transform
          lines.push(`    layer_${layerIndex}.property('Transform').property('Position').setValue([compWidth / 2, compHeight / 2]);`);
          if (clip.scale !== 1.0) {
            lines.push(`    layer_${layerIndex}.property('Transform').property('Scale').setValue([${(clip.scale * 100).toFixed(1)}, ${(clip.scale * 100).toFixed(1)}]);`);
          }
        }

        if (track.type.startsWith("AUDIO") && volumeDb !== 0) {
          lines.push(`    var audioProp_${layerIndex} = layer_${layerIndex}.property('Audio');`);
          lines.push(`    if (audioProp_${layerIndex}) {`);
          lines.push(`      audioProp_${layerIndex}.property('Audio Levels').setValue([${volumeDb.toFixed(1)}, ${volumeDb.toFixed(1)}]);`);
          lines.push(`    }`);
        }

        lines.push(`  } catch (errClip_${layerIndex}) {`);
        lines.push(`    $.writeln('Warning importing clip ${this.escapeString(clip.label)}: ' + errClip_${layerIndex}.toString());`);
        lines.push(`  }`);
        lines.push("");
        layerIndex++;
      }
    }

    lines.push("  app.endUndoGroup();");
    lines.push("} catch (fatalError) {");
    lines.push("  app.endUndoGroup();");
    lines.push("  alert('Fatal Error building composition: ' + fatalError.toString());");
    lines.push("}");
    lines.push("");

    return lines.join("\n");
  }

  private static escapeString(str: string): string {
    return str.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
  }
}
