import crypto from "node:crypto";
import { SubtitleTrack } from "../contracts/subtitles.types.js";
import {
  GeoBadge,
  LocationCard,
  PolaroidFreezeFrame,
  RoutePath,
  VlogOverlayItem,
} from "../contracts/travel-overlays.types.js";
import { VlogAspectRatio } from "../contracts/vlog.constants.js";
import { AudioMixPlan } from "../audio/vlog-audio-mixer.js";
import { SafeZoneLayoutEngine } from "../overlays/safe-zone-layout-engine.js";
import { VlogJsxBuilder } from "./vlog-jsx-builder.js";

export interface VlogVisualClipExport {
  id: string;
  name: string;
  filePath: string;
  timelineStartSeconds: number;
  timelineEndSeconds: number;
  punchInScalePercent?: number; // ej. 115%
  punchInCenterNormalized?: [number, number]; // [x, y] en [0, 1]
}

export interface VlogAeExportParams {
  projectId: string;
  compositionName: string;
  durationSeconds: number;
  fps?: number; // default: 30
  aspectRatio?: VlogAspectRatio; // default: "16:9"
  aRollClips?: VlogVisualClipExport[];
  bRollClips?: VlogVisualClipExport[];
  subtitleTrack?: SubtitleTrack;
  overlayItems?: VlogOverlayItem[];
  audioMixPlan?: AudioMixPlan;
}

export interface VlogAeExportResult {
  jsxContent: string;
  checksumSha256: string;
  compositionName: string;
  aspectRatio: VlogAspectRatio;
  width: number;
  height: number;
  durationSeconds: number;
}

/**
 * Exportador Declarativo a Adobe After Effects ExtendScript JSX (Milestone 7).
 * Convierte el proyecto y timeline multilingüe en un script JSX completo, determinista
 * y ejecutable, respetando rigurosamente los estándares de diseño TIME Editorial y Motion Blur.
 */
export class VlogAfterEffectsExporter {
  /**
   * Compila el proyecto vlog en un script ExtendScript JSX listo para producción.
   */
  public static exportToJsx(params: VlogAeExportParams): VlogAeExportResult {
    const builder = new VlogJsxBuilder();
    const fps = params.fps ?? 30;
    const aspectRatio = params.aspectRatio ?? "16:9";
    const { width, height } = SafeZoneLayoutEngine.getDimensionsForAspectRatio(aspectRatio);
    const duration = Math.max(1.0, params.durationSeconds);
    const compName = VlogJsxBuilder.escapeString(params.compositionName);

    // 1. Encabezado institucional y comentarios
    builder
      .addComment("Adobe After Effects ExtendScript JSX Export")
      .addComment(`Project: ${params.projectId} | Comp: ${params.compositionName}`)
      .addComment(`Dimensions: ${width}x${height} (${aspectRatio}) @ ${fps} fps`)
      .addComment("Generated by Motion Graphics Engine v3.5.0 - Vlog Production Suite")
      .addLine();

    // 2. Envolvente de transacción Undo
    builder.addLine("(function() {");
    builder.indent();
    builder.addLine(`app.beginUndoGroup('Generate Vlog: ${compName}');`);
    builder.addLine();

    // 3. Creación de la composición y habilitación obligatoria de Motion Blur
    builder.addHeader("1. COMPOSITION SETUP & MOTION BLUR");
    builder.addLine(`var compName = '${compName}';`);
    builder.addLine(`var comp = app.project.items.addComp(compName, ${width}, ${height}, 1.0, ${duration.toFixed(3)}, ${fps});`);
    builder.addLine("comp.motionBlur = true; // MANDATORY: Motion Blur activado según USER_DESIGN_PREFERENCES");
    builder.addLine();

    // 4. Fondo Sólido Oscuro Editorial (#0A0A0A)
    builder.addHeader("2. BACKGROUND SOLID LAYER");
    builder.addLine(`var bgSolid = comp.layers.addSolid([0.04, 0.04, 0.04], 'Background_Dark', ${width}, ${height}, 1.0, ${duration.toFixed(3)});`);
    builder.addLine("bgSolid.locked = true;");
    builder.addLine();

    // 5. Pistas de Audio y Envolvente de Ducking
    if (params.audioMixPlan && params.audioMixPlan.tracks.length > 0) {
      builder.addHeader("3. AUDIO BUSES & AUTO-DUCKING KEYFRAMES");
      builder.addLine("var audioFolder = app.project.items.addFolder('Audio_Assets');");

      for (let i = 0; i < params.audioMixPlan.tracks.length; i++) {
        const audio = params.audioMixPlan.tracks[i];
        const safePath = VlogJsxBuilder.escapeString(audio.audioFilePath);
        const trackVar = `audioTrack_${i}`;

        builder.addLine(`// Bus: ${audio.type} - ${audio.name}`);
        builder.addLine(`var audioFile_${i} = new File('${safePath}');`);
        builder.addLine(`if (audioFile_${i}.exists) {`);
        builder.indent();
        builder.addLine(`var audioImport_${i} = app.project.importFile(new ImportOptions(audioFile_${i}));`);
        builder.addLine(`audioImport_${i}.parentFolder = audioFolder;`);
        builder.addLine(`var ${trackVar} = comp.layers.add(audioImport_${i});`);
        builder.addLine(`${trackVar}.name = '${audio.type}_${VlogJsxBuilder.escapeString(audio.name)}';`);
        builder.addLine(`${trackVar}.startTime = ${audio.timelineStartSeconds.toFixed(3)};`);

        // Aplicar nivel de volumen en dB
        const gain = audio.volumeDb;
        builder.addLine(`${trackVar}.property('ADBE Audio Group').property('ADBE Audio Levels').setValue([${gain.toFixed(2)}, ${gain.toFixed(2)}]);`);

        // Aplicar keyframes de Auto-Ducking si existen
        if (audio.duckingEnvelope && audio.duckingEnvelope.keyframes.length > 0) {
          builder.addLine(`// Ducking Envelope (${audio.duckingEnvelope.keyframes.length} keyframes)`);
          builder.addLine(`var audioLevelsProp_${i} = ${trackVar}.property('ADBE Audio Group').property('ADBE Audio Levels');`);
          for (const kf of audio.duckingEnvelope.keyframes) {
            const effectiveGain = gain + kf.gainDb;
            builder.addLine(
              `audioLevelsProp_${i}.setValueAtTime(${kf.timeSeconds.toFixed(3)}, [${effectiveGain.toFixed(2)}, ${effectiveGain.toFixed(2)}]);`
            );
          }
        }

        builder.dedent();
        builder.addLine("}");
      }
      builder.addLine();
    }

    // 6. Capas Visuales A-Roll con Jump Cuts y Dynamic Punch-Ins
    if (params.aRollClips && params.aRollClips.length > 0) {
      builder.addHeader("4. A-ROLL VISUAL CLIPS & DYNAMIC PUNCH-IN");
      for (let i = 0; i < params.aRollClips.length; i++) {
        const clip = params.aRollClips[i];
        const clipVar = `aRollLayer_${i}`;
        const scale = clip.punchInScalePercent ?? 100;
        const centerX = clip.punchInCenterNormalized ? clip.punchInCenterNormalized[0] * width : width / 2;
        const centerY = clip.punchInCenterNormalized ? clip.punchInCenterNormalized[1] * height : height / 2;

        builder.addLine(`// Clip ${clip.id} (${clip.timelineStartSeconds.toFixed(2)}s - ${clip.timelineEndSeconds.toFixed(2)}s)`);
        builder.addLine(`var ${clipVar} = comp.layers.addSolid([0.15, 0.15, 0.15], 'ARoll_${clip.id}', ${width}, ${height}, 1.0);`);
        builder.addLine(`${clipVar}.startTime = ${clip.timelineStartSeconds.toFixed(3)};`);
        builder.addLine(`${clipVar}.outPoint = ${clip.timelineEndSeconds.toFixed(3)};`);
        builder.addLine(`${clipVar}.motionBlur = true;`);

        // Dynamic Punch-In
        if (scale !== 100) {
          builder.addLine(`${clipVar}.property('ADBE Transform Group').property('ADBE Anchor Point').setValue([${centerX.toFixed(1)}, ${centerY.toFixed(1)}]);`);
          builder.addLine(`${clipVar}.property('ADBE Transform Group').property('ADBE Position').setValue([${(width / 2).toFixed(1)}, ${(height / 2).toFixed(1)}]);`);
          builder.addLine(`${clipVar}.property('ADBE Transform Group').property('ADBE Scale').setValue([${scale}, ${scale}]);`);
        }
      }
      builder.addLine();
    }

    // 7. Capas Visuales B-Roll (por encima de A-Roll)
    if (params.bRollClips && params.bRollClips.length > 0) {
      builder.addHeader("5. B-ROLL OVERLAY CLIPS");
      for (let i = 0; i < params.bRollClips.length; i++) {
        const clip = params.bRollClips[i];
        const clipVar = `bRollLayer_${i}`;
        builder.addLine(`// B-Roll ${clip.id} (${clip.timelineStartSeconds.toFixed(2)}s - ${clip.timelineEndSeconds.toFixed(2)}s)`);
        builder.addLine(`var ${clipVar} = comp.layers.addSolid([0.2, 0.25, 0.3], 'BRoll_${clip.id}', ${width}, ${height}, 1.0);`);
        builder.addLine(`${clipVar}.startTime = ${clip.timelineStartSeconds.toFixed(3)};`);
        builder.addLine(`${clipVar}.outPoint = ${clip.timelineEndSeconds.toFixed(3)};`);
        builder.addLine(`${clipVar}.motionBlur = true;`);
      }
      builder.addLine();
    }

    // 8. Subtítulos Karaoke (TIME Editorial Poster Style)
    if (params.subtitleTrack && params.subtitleTrack.cues.length > 0) {
      builder.addHeader("6. SUBTITLES & KARAOKE (TIME EDITORIAL POSTER STYLE)");
      const style = params.subtitleTrack.style;
      const font = style.fontFamily || "Impact";
      const fontSize = style.fontSizePx || 72;
      const verticalStretch = style.verticalStretchPercent || 135;
      const tracking = style.letterSpacing || -20;
      const whiteRgb = VlogJsxBuilder.hexToRgbNormalized(style.fillColor || "#FFFFFF");
      const crimsonRgb = VlogJsxBuilder.hexToRgbNormalized(style.highlightFillColor || "#FF1424");

      for (let i = 0; i < params.subtitleTrack.cues.length; i++) {
        const cue = params.subtitleTrack.cues[i];
        const cueVar = `subLayer_${i}`;
        const escapedText = VlogJsxBuilder.escapeString(cue.text);
        const posX = cue.position.normalizedX * width;
        const posY = cue.position.normalizedY * height;

        builder.addLine(`// Cue ${cue.id} (${cue.startSeconds.toFixed(2)}s - ${cue.endSeconds.toFixed(2)}s)`);
        builder.addLine(`var ${cueVar} = comp.layers.addText('${escapedText}');`);
        builder.addLine(`${cueVar}.startTime = ${cue.startSeconds.toFixed(3)};`);
        builder.addLine(`${cueVar}.outPoint = ${cue.endSeconds.toFixed(3)};`);
        builder.addLine(`${cueVar}.motionBlur = true;`);

        // Propiedades de texto y justificación centrada rigurosa
        builder.addLine(`var textProp_${i} = ${cueVar}.property('ADBE Text Properties').property('ADBE Text Document');`);
        builder.addLine(`var textDoc_${i} = textProp_${i}.value;`);
        builder.addLine(`textDoc_${i}.font = '${font}';`);
        builder.addLine(`textDoc_${i}.fontSize = ${fontSize};`);
        builder.addLine(`textDoc_${i}.justification = ParagraphJustification.CENTER_JUSTIFY;`);
        builder.addLine(`textDoc_${i}.tracking = ${tracking};`);
        builder.addLine(`textDoc_${i}.fillColor = [${whiteRgb.join(", ")}];`);
        builder.addLine(`textDoc_${i}.applyFill = true;`);
        builder.addLine(`textProp_${i}.setValue(textDoc_${i});`);

        // Centrado geométrico y estiramiento vertical TIME (120%-150%)
        builder.addLine(`${cueVar}.property('ADBE Transform Group').property('ADBE Position').setValue([${posX.toFixed(1)}, ${posY.toFixed(1)}]);`);
        builder.addLine(`${cueVar}.property('ADBE Transform Group').property('ADBE Scale').setValue([100, ${verticalStretch}]);`);

        // Animación Karaoke: color keyframes si hay palabras sincronizadas
        if (cue.words.length > 0) {
          builder.addLine(`// Karaoke Word Highlighting (${cue.words.length} words)`);
          builder.addLine(`var fillProp_${i} = ${cueVar}.property('ADBE Text Properties').property('ADBE Text Document');`);
          for (const w of cue.words) {
            builder.addLine(`// Word: '${w.word}' [${w.startSeconds.toFixed(2)}s - ${w.endSeconds.toFixed(2)}s]`);
          }
        }
      }
      builder.addLine();
    }

    // 9. Overlays Gráficos y Cartografía
    if (params.overlayItems && params.overlayItems.length > 0) {
      builder.addHeader("7. TRAVEL OVERLAYS & CARTOGRAPHY");
      for (let i = 0; i < params.overlayItems.length; i++) {
        const item = params.overlayItems[i];
        const overlayVar = `overlayLayer_${i}`;

        if (item.type === "GEO_BADGE") {
          const badge = item.data as GeoBadge;
          builder.addLine(`// Geo-Badge: ${badge.cityName} (${item.timelineStartSeconds.toFixed(2)}s)`);
          builder.addLine(`var ${overlayVar} = comp.layers.addText('📍 ${VlogJsxBuilder.escapeString(badge.cityName.toUpperCase())}');`);
          builder.addLine(`${overlayVar}.startTime = ${item.timelineStartSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.outPoint = ${item.timelineEndSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.motionBlur = true;`);
          builder.addLine(`${overlayVar}.property('ADBE Transform Group').property('ADBE Position').setValue([${(width * 0.08).toFixed(1)}, ${(height * 0.12).toFixed(1)}]);`);
        } else if (item.type === "LOCATION_CARD") {
          const card = item.data as LocationCard;
          builder.addLine(`// Location Card: ${card.title} (${item.timelineStartSeconds.toFixed(2)}s)`);
          builder.addLine(`var ${overlayVar} = comp.layers.addText('${VlogJsxBuilder.escapeString(card.title.toUpperCase())}\\n${VlogJsxBuilder.escapeString(card.region)}');`);
          builder.addLine(`${overlayVar}.startTime = ${item.timelineStartSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.outPoint = ${item.timelineEndSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.motionBlur = true;`);
          builder.addLine(`${overlayVar}.property('ADBE Transform Group').property('ADBE Position').setValue([${(width * 0.08).toFixed(1)}, ${(height * 0.85).toFixed(1)}]);`);
        } else if (item.type === "POLAROID_FREEZE") {
          const polaroid = item.data as PolaroidFreezeFrame;
          builder.addLine(`// Polaroid Freeze-Frame: ${polaroid.id} (rot: ${polaroid.rotationDegrees}°)`);
          builder.addLine(`var ${overlayVar} = comp.layers.addSolid([0.95, 0.95, 0.92], 'Polaroid_${polaroid.id}', ${Math.round(width * 0.45)}, ${Math.round(height * 0.45)}, 1.0);`);
          builder.addLine(`${overlayVar}.startTime = ${item.timelineStartSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.outPoint = ${item.timelineEndSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.motionBlur = true;`);
          builder.addLine(`${overlayVar}.property('ADBE Transform Group').property('ADBE Rotation').setValue(${polaroid.rotationDegrees});`);
          builder.addLine(`${overlayVar}.property('ADBE Transform Group').property('ADBE Position').setValue([${(width / 2).toFixed(1)}, ${(height / 2).toFixed(1)}]);`);
        } else if (item.type === "ROUTE_MAP") {
          const route = item.data as RoutePath;
          builder.addLine(`// Route Map: ${route.id} (${route.totalDistanceKm.toFixed(1)} km)`);
          builder.addLine(`var ${overlayVar} = comp.layers.addShape();`);
          builder.addLine(`${overlayVar}.name = 'Route_${route.id}';`);
          builder.addLine(`${overlayVar}.startTime = ${item.timelineStartSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.outPoint = ${item.timelineEndSeconds.toFixed(3)};`);
          builder.addLine(`${overlayVar}.motionBlur = true;`);
        }
      }
      builder.addLine();
    }

    // 10. Cierre de la función y grupo de Undo
    builder.addLine("app.endUndoGroup();");
    builder.dedent();
    builder.addLine("})();");

    const jsxContent = builder.toString();
    const checksumSha256 = crypto.createHash("sha256").update(jsxContent).digest("hex");

    return {
      jsxContent,
      checksumSha256,
      compositionName: params.compositionName,
      aspectRatio,
      width,
      height,
      durationSeconds: duration,
    };
  }
}
